function init(self)
    msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
    if action_id == hash("zoom_up") then
    	msg.post("@render:", "zoom", {value=0.2})
    elseif action_id == hash("zoom_down") then
    	msg.post("@render:", "zoom", {value=-0.2})
    end
    if action_id == hash("mouse2") and not action.pressed then
    	if screen_dx ~= 0 or screen_dy ~= 0 then
    		msg.post("@render:", "scroll", { dx = -action.screen_dx, dy = -action.screen_dy})
    	end
    end
end
